name = "synd-dgf-chatkit-token"
main = "worker.js"
compatibility_date = "2025-10-15"

# Cloudflare Workers configuration for ChatKit token generation
# This worker runs on Cloudflare's edge network for low latency

[env.production]
# Production environment variables
# Note: Secrets must be set via CLI, not in this file
# Use: wrangler secret put OPENAI_API_KEY
# Use: wrangler secret put CHATKIT_WORKFLOW_ID

vars = { 
  DEBUG = "false",
  # Default requests per minute per origin (fallback)
  DEFAULT_ORIGIN_QUOTA = "60",
  # Optional per-client (browser) requests per minute cap
  CLIENT_PER_MIN_LIMIT = "20",
  # JSON mapping for per-origin quotas (host -> rpm)
  ORIGIN_QUOTAS_JSON = "{\"digitalhealthcrc.github.io\":30,\"localhost:8000\":15,\"127.0.0.1:8000\":15}"
}

# KV namespace for global rate limiting (set your IDs)
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "RATE_LIMIT_KV_ID_PLACEHOLDER"
preview_id = "RATE_LIMIT_KV_PREVIEW_ID_PLACEHOLDER"

[env.staging]
vars = { 
  DEBUG = "true",
  DEFAULT_ORIGIN_QUOTA = "60",
  CLIENT_PER_MIN_LIMIT = "20",
  ORIGIN_QUOTAS_JSON = "{\"digitalhealthcrc.github.io\":30,\"localhost:8000\":15,\"127.0.0.1:8000\":15}"
}

# Deployment configuration
[build]
command = ""

# Routes configuration (optional - if you want a custom domain)
# routes = [
#   { pattern = "chat.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]
