name = "synd-dgf-chatkit-token"
main = "worker.js"
compatibility_date = "2025-10-15"

# Cloudflare Workers configuration for ChatKit token generation
# This worker runs on Cloudflare's edge network for low latency

[env.production]
# Production environment variables
# Note: Secrets must be set via CLI, not in this file
# Use: wrangler secret put OPENAI_API_KEY
# Use: wrangler secret put CHATKIT_WORKFLOW_ID

vars = { DEBUG = "false" }

# Optional: KV namespace for rate limiting
# Uncomment and configure if you want enhanced rate limiting
# [[kv_namespaces]]
# binding = "RATE_LIMIT_KV"
# id = "YOUR_KV_NAMESPACE_ID"

[env.staging]
vars = { DEBUG = "true" }

# Deployment configuration
[build]
command = ""

# Routes configuration (optional - if you want a custom domain)
# routes = [
#   { pattern = "chat.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]
